### ISSUE TITLE
Show Loading... while fetching from remote url

### ISSUE THREAD

**Issue by hellotunmbi** [hellotunmbi/giphy-experiment#2]
When Trending is clicked or Search is performed, the display component should show "Loading..." so as to tell the user to wait while it fetches

**Comment by nitish24p** [comment]
Will pick this up

**Comment by hellotunmbi** [comment]
Oh thanks Nitish.

Much appreciated

On Sep 30, 2017 7:47 PM, "Nitish Phanse" <notifications@github.com> wrote:

Will pick this up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/hellotunmbi/giphy-experiment/issues/2#issuecomment-333328196>,
or mute the thread

**Comment by nitish24p** [comment]
Don't have access writes to push to a branch

**Comment by nitish24p** [comment]
https://github.com/hellotunmbi/giphy-experiment/pull/4
