### ISSUE TITLE
Better UI

### ISSUE THREAD

**Issue by hellotunmbi** [hellotunmbi/giphy-experiment#3]
For now, the layout looks very simple. I'll like it to look nicer.

Thanks

**Comment by alkesh47** [comment]
Can you be a little more specific as to how you want the UI to be?

**Comment by shubhmisaki** [comment]
Can I work upon this?

**Comment by harshini1** [comment]
@hellotunmbi  Is this still open?

**Comment by hellotunmbi** [comment]
@harshini1 No its not. Thanks
